version: '3.9'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app/
    ports:
      - "8000:8000"
    #  requirements:
    #    - ./.env.dev